// <auto-generated />
namespace Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addonetomanyrelationbetweenusersandwishes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addonetomanyrelationbetweenusersandwishes));
        
        string IMigrationMetadata.Id
        {
            get { return "201705100610262_Add one-to-many relation between users and wishes."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
